alias: MQTT Sensor Averages
description: ""
trigger:
  - platform: time_pattern
    minutes: "*"
condition: []
action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: sensor-averages
      payload_template: |-
        {
          "averages": {
              "temperature": [{%- for i in range(0,24) -%}
                              {{ states("sensor.ns_avg_temp_" ~ i) }}
                              {%-if not loop.last %},{% endif -%}
                              {% endfor -%}],
              "humidity": [{%- for i in range(0,24) -%}
                           {{ states("sensor.ns_avg_humidity_" ~ i) }}
                           {%-if not loop.last %},{% endif -%}
                           {% endfor -%}],
              "co2": [{%- for i in range(0,24) -%}
                      {{ states("sensor.ns_avg_co2_" ~ i) }}
                      {%-if not loop.last %},{% endif -%}
                      {% endfor -%}],
              "voc": [{%- for i in range(0,24) -%}
                      {{ states("sensor.ns_avg_voc_" ~ i) }}
                      {%-if not loop.last %},{% endif -%}
                      {% endfor -%}]
          }
        }
mode: single
