alias: MQTT Sport Updates
description: Publish Team Tracker attributes as JSON
trigger:
  - platform: state
    entity_id:
      - sensor.teamtracker_latest_update
    enabled: true
  - platform: mqtt
    topic: teamtracker/start
condition: []
action:
  - service: mqtt.publish
    data:
      qos: 0
      topic: teamtracker/all
      payload_template: |-
        {
          "teams": [
          {%- for team in expand("group.teamtracker_teams") %}
          {
            "team_abbr": "{{ state_attr(team.entity_id, 'team_abbr') }}",
            "league": "{{ state_attr(team.entity_id, 'league') }}",
            "state": "{{ states(team.entity_id) }}",
            "attributes": {{ team.attributes|to_json() }} 
          }{% if not loop.last %},{% endif %}
          {%- endfor %}
          ]
        }
mode: queued
max: 20
