version: 1

formatters:
  standard:
    format: "%(asctime)s | %(name)s | %(levelname)s :: %(message)s"
  error:
    format: "%(asctime)s | %(name)s | %(filename)s:%(lineno)s | %(levelname)s :: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  info_file_handler:
    (): 'ext://utils.owned_file_handler' 
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ../logs/info.log
    maxBytes: 5242880 # 5MB
    backupCount: 10
    encoding: utf8
    owner: [dj, dj]
  error_file_handler:
    (): 'ext://utils.owned_file_handler' 
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ../logs/error.log
    maxBytes: 5242880 # 5MB
    backupCount: 10
    encoding: utf8
    owner: [dj, dj]
root:
  level: DEBUG
  handlers: [console,info_file_handler,error_file_handler]
  propogate: yes
